name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '^1.22.1'
        id: go
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Test
        run: go test ./...
