name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go 1.22.1
        uses: actions/setup-go@v4
        with:
          go-version: '^1.22.1'
        id: go
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o summairpg-linux cmd/summairpg/main.go
      - name: Build darwin
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -v -o summairpg-darwin cmd/summairpg/main.go
      - name: Build windows
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -o summairpg.exe cmd/summairpg/main.go
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            summairpg-linux
            summairpg-darwin
            summairpg.exe
